### PR TITLE
log installation and execution information

### PR DESCRIPTION
**Pull request by gillesdegottex**

### CODE REVIEW

**Comment by ronanki** [comment]
why "import socket" in middle of the code but not in the header?

**Comment by gillesdegottex** [comment]
Fixed

**Comment by ronanki** [comment]
I have commented few lines in the latest commit, as I have seen two issues:

1. env_PYTHONPATHs = os.getenv('PYTHONPATH').split(':')
if PYTHHONPATH is None, the above statement throws an error.

2. subprocess.check_output is a valid function only for python versions > 2.7, otherwise throws an error with python 2.6.6

**Comment by gillesdegottex** [comment]
I created a new pull request with fixes for both 1. and 2.

**Pull request merged**
