### PR TITLE
Simplify conf files generation for #1

### PR DESCRIPTION
**Pull request by gillesdegottex**
Two extra questions:
1) Is it necessary to keep egs/slt_arctic/s1/conf/global_settings.cfg ? Since it is generated, I think it would be better to remove it from the repo.
2) When refactoring prepare_config_files_for_synthesis.sh, I've noticed that "enforce_silence" was set to True only for test_synth_${Voice}.conf. Not for test_dur_synth_${Voice}.conf, neither for duration_${Voice}.conf and acoustic_${Voice}.conf. That's normal?

### CODE REVIEW

**Comment by ronanki** [comment]
1) global_settings.cfg can be removed -- that was uploaded along with other conf files. Anyhow, it will be replaced as soon as the user runs one of the codes (./run_demo.sh or ./run_full_voice.sh).  

2) Yes -- that means, both acoustic model and duration model are trained by removing silence from all training files. And also during synthesis, silence duration is not predicted but silence is synthesized for final waveform generation.

**Comment by gillesdegottex** [comment]
Great, thanks for the explanations.

**Comment by ronanki** [comment]
Hi,

I just got back from states, a couple of days before. There is some conflict to merge the pull request. Will sort it out and merge soon.

**Comment by gillesdegottex** [comment]
No worry, leave it, I'll do it ASAP. Cheers

**Pull request merged**
