### PR TITLE
REAPER f0 extraction integrated.

### PR DESCRIPTION
**Pull request by felipeespic**

### CODE REVIEW

**Comment by dreamk73** [comment]
I downloaded this code and was able to extract F0 values with Reaper and train merlin models with it. I am wondering with the way that the World vocoder uses the F0 whether the mgc and bap features should be computed afterwards with the new Reaper F0 values? I will investigate this further.

**Comment by m-toman** [comment]
@dreamk73 Interesting idea. I found that REAPER produces better results in most cases. If I find the time I'll also look into that.

Regarding https://github.com/CSTR-Edinburgh/merlin/pull/265/commits/8bd5f071ab3ffac8c409e32128d2934953d56fc4#diff-359763ab2df64fe91e4a3ac2560810ddR142
I saw that REAPER typically produces a few frames less than WORLD. I solved it by appending the corresponding frames from the WORLD results.

I've also tried setting the min/max values for REAPER using the F0 statistics from WORLD but I didn't find any significant differences.

**Comment by dreamk73** [comment]
This is just for one voice. But I rewrote the analysis.cpp code from WORLD to read in the REAPER F0 and then produce the ap and sp features and the objective measures are slightly better than when you just get the WORLD parameters and change out the DIO F0 with the REAPER F0

|_. Voice |_. MCD |_. BAP |_. F0 RMSE |_. F0 CORR |_. F0 VUV |
| en_au male 48kHz reaper + WORLD ap/sp | 4.672 dB | 0.281 dB | 13.089 Hz | 0.819 | 5.519% |
| en_au male 48kHz reaper -> WORLD ap/sp | 4.680 dB | 0.243 dB | 12.956 Hz | 0.822 | 5.479% |

**Comment by dreamk73** [comment]
Also, has someone tried to integrate the newer Harvest F0 extraction from WORLD? It seems to be computing a continuous F0 curve, so we probably need to add some postprocessing to set unvoiced frames to 0?

For the same data set as above I get:
MCD: 4.713 dB; BAP: 0.004 dB; F0:- RMSE: 17.260 Hz; CORR: 0.588; VUV: 11.355%
The low BAP error and the buzziness in the waveforms are dead giveaways.

**Comment by ronanki** [comment]
@dreamk73 Sometimes, the objective scores may not reveal everything (or misleading) -- you should do perceptual evaluation as well.

**Comment by dreamk73** [comment]
Very true, @ronanki. Listening to the generated audio, I don't hear any difference. So I guess it is fine to compute F0 separately and not worry about feeding the new F0 to the WORLD ap and sp analysis algorithms.

**Pull request merged**
